version: '3'
services:
  react-nginx:
    image: trzl/portfolio:mytimes-react.1
    restart: unless-stopped
    container_name: mytimes-nginx
    networks:
      - mytimes
    env_file: .env
    environment:
      - NODE_ENV=production
  reverseproxy:
    image: trzl/portfolio:mytimes-proxy.1
    container_name: mytimes-proxy
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    depends_on:
      - react-nginx
   environment:
      VIRTUAL_HOST: mytimes.tbrownkcdev.com
      LETSENCRYPT_HOST: mytimes.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
  mytimes:
    driver: bridge